### ISSUE TITLE
配置网页天气插件的时候出现问题

### ISSUE THREAD

**Issue by w4ctech** [thinkpage/api-demos#16]
https://www.seniverse.com/widget/get

![image](https://user-images.githubusercontent.com/33955669/54590533-49176b00-4a63-11e9-9b30-eafb74ceb6a9.png)

**Comment by ecmadao** [comment]
@w4ctech 
感谢反馈。插件遭到恶意攻击，正在修复中

**Comment by ecmadao** [comment]
@w4ctech 
已修复，感谢反馈
