### ISSUE TITLE
-----

### ISSUE THREAD

**Issue by hjkl66** [thinkpage/api-demos#6]
var sig = CryptoJS.HmacSHA1(str, KEY).toString(CryptoJS.enc.Base64);没找到方法

**Comment by ecmadao** [comment]
@huangliao 
CryptoJS 文件在[这里](https://github.com/seniverse/seniverse-api-demos/blob/master/javascript/scripts/hmac-sha1.js)
在 JavaScript 的 demo 里，在 HTML 中引入了该文件。请检查一下是否正确引用，以及路径是否正确？
