### ISSUE TITLE
Origin 'http://127.0.0.1:8020' is therefore not allowed access.

### ISSUE THREAD

**Issue by albertcsg** [thinkpage/api-demos#7]
如您所述，我在我的服务里绑定了域名127.0.0.1,本地跑的项目以127.0.0.1:8020开头，可是
出现如下问题：
XMLHttpRequest cannot load http://api.seniverse.com/v3/weather/now.json?location=%E5%8D%97%E6%B2%99&ts…502083719&uid=uid&sig=sign&callback=foo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8020' is therefore not allowed access.
我查了下 是跨域问题，但是我已经这么做了啊。
另外，代理已关。

**Comment by ecmadao** [comment]
@ajjing 
你是纯前端来访问的吗？如果是的话，请通过 jsonp 的方式获取数据，否则请求将会被浏览器拦截。jsonp
 访问的具体代码可见这里: [jsonp.html](https://github.com/seniverse/seniverse-api-demos/blob/master/javascript/jsonp.html)

**Comment by albertcsg** [comment]
ok可以了 谢谢~
